# Introducción a ```Numpy```

```Numpy``` es una de la biblioteca básica necesia para el desarrollo de computo científico. La caul contiene entre otras cosas:

* Un poderoso objeto de matriz N-dimensional.
* Funciones sofisticadas.
* Herramientas para la integración de código C / C ++ y Fortran.
* Álgebra lineal, transformada de Fourier y diferentes funciones de números aleatorios.

Además de sus obvios usos científicos, NumPy también se puede usar como un eficiente contenedor multidimensional de datos genéricos. Se pueden definir tipos de datos arbitrarios. Esto permite que NumPy se integre a la perfección con una amplia variedad de bases de datos.

NumPy está bajo la licencia BSD, lo que permite su reutilización con pocas restricciones.  

En ```numpy``` podemos encontar funciones muy útiles como las funciones trigonométricas:

In [1]:
sin(0)

NameError: name 'sin' is not defined

en ```numpy``` también se encuentran algunas constantes muy importantes tal como $\pi$

In [2]:
pi

NameError: name 'pi' is not defined

In [4]:
fac(4)

NameError: name 'fac' is not defined

In [5]:
import myLib

In [6]:
myLib.factorial(5)

120

In [7]:
import numpy

In [8]:
numpy.pi

3.141592653589793

In [9]:
numpy.cos(numpy.pi/2)

6.123233995736766e-17

In [10]:
from numpy import *

In [11]:
cos(pi/2)

6.123233995736766e-17

In [13]:
?numpy

En ```numpy```tenemos un tipo llamado ```array``` el cual definimos como 

In [14]:
a = array([0,1,2,3,4,5,6,7])

In [15]:
type(a)

numpy.ndarray

In [16]:
a[4]

4

Si recordamos el método ```range(n)``` generaba enteros del $0$ a $n$. Pues en ```numpy``` tenemos análogo que nos genera un ```array``` de con enteros de $0$ a $n$

In [17]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arange(3,11)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arange(3,21,3)

array([ 3,  6,  9, 12, 15, 18])

Además con el método ```arange()``` podemos especificar de tipo de variable, estos tipo pueden ser.

* ```bool``` Booleano (Verdadero o Falso) almacenado como un bit
* ```inti``` Platform integer (normalmente int32 o int64)
* ```int8``` Byte (-128 a 127)
* ```int16``` Entero (-32768 a 32767)
* ```int32``` Entero (-2 ** 31 a 2 ** 31 -1)
* ```int64``` Entero (-2 ** 63 a 2 ** 63 -1)
* ```uint8``` Entero sin signo (0 a 255)
* ```uint16``` Entero sin signo (0 a 65535)
* ```uint32``` Entero sin signo (0 a 2 ** 32 - 1)
* ```uint64``` Entero sin signo (0 a 2 ** 64 - 1)
* ```float16``` flotante de precisión media: bit de signo, exponente de 5 bits, mantisa de 10 bits
* ```float32``` Flotante de precisión simple: bit de signo, exponente de 8 bits, mantisa de 23 bits
* ```float64``` o ```float``` Doble precisión flotante: bit de signo, exponente de 11 bits, mantisa de 52 bits
* ```complex64``` Número complejo, representado por dos flotantes de 32 bits (componentes reales e imaginarios)
* ```complex12``` o ```complex```, representado por dos flotantes de 64 bits (componentes reales e imaginarios)

In [24]:
arange(2, dtype=bool)

array([False,  True])

In [25]:
arange(7, dtype=uint16)

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [26]:
arange(7, dtype=float64)

array([0., 1., 2., 3., 4., 5., 6.])

In [27]:
lista1 = [0., 1., 2., 3., 4., 5., 6.]

In [31]:
3*lista1 + [2,2,2]

[0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 2,
 2,
 2]

 Un atributo importante de ```array``` es ```shape``` que practicamente nos proporciona la forma del ```array```

In [32]:
a =arange(24)

In [34]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
a.shape

(24,)

Algo que es muy útil es que podemos cambiar la forma de un ```array``` con el método ```reshape``` por ejemplo:

In [36]:
M=arange(9).reshape(3,3)

In [38]:
M + M

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

Si observamos en la celda anterior vemos que un ```array``` podría suele ser muy útil para definir matrices, es decir:

In [39]:
N=array([[1,3],[5,8],[4,5]])

In [40]:
type(N)

numpy.ndarray

In [41]:
N[0]

array([1, 3])

In [42]:
N[2,1]

5

In [43]:
N[2,:]

array([4, 5])

In [45]:
transpose(N[:,0])

array([1, 5, 4])

Y no sólo podemos definir matrices, sino estructura más sofisticadas como tensores.

In [46]:
T=arange(24).reshape(2,3,4)

In [47]:
T

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [52]:
T[0,0, 2]

2

In [53]:
T[:,0,1]

array([ 1, 13])

In [54]:
T[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Para notar el poder de los ```array```'s recordemos que pasaba si a una lista la multiplicabamos por un entero o un flotante:

In [55]:
l1 = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [56]:
l1

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [57]:
3*l1

[[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8],
 [0, 1, 2],
 [3, 4, 5],
 [6, 7, 8],
 [0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]]

In [58]:
3.0*l1

TypeError: can't multiply sequence by non-int of type 'float'

Ahora veamos que pasa si a un ```array``` los multiplcamos por enteros o flotantes

In [59]:
3*M

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [60]:
5.0*M

array([[ 0.,  5., 10.],
       [15., 20., 25.],
       [30., 35., 40.]])

## Algunos atributos y métodos

### ```ndim``` 

Da el número de dimensiones

In [61]:
a.ndim

1

In [62]:
M.ndim

2

### ```size```

Da el número de elementos

In [63]:
 a.size

24

In [64]:
 M.size

9

### ```itemsize``` 

Da el número de bit de cada elemto en el ```array```

In [65]:
a.itemsize

8

In [66]:
M.itemsize

8

### ```resize``` 

In [67]:
a.resize(6,4)

In [68]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### ```T``` 

Transpone el ```array```

In [69]:
a.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

## Álgebra lineal

Como mencinamos al inicio ```numpy``` cuenta con una importante librería de álgebra lineal. Comencemos por crear la matiz identidad de dimensión n:

In [75]:
i2=eye(5)
i2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Además podemos guardar los datos con la función savetxt. Obviamente, necesitamos especificar el nombre del archivo en el que queremos guardar los datos y la matriz que contiene los datos en sí:

In [76]:
savetxt("eye.txt", i2)

Las matrices se pueden crear con la función ```mat```. Esta función no hace una copia si la entrada ya es una ```matrix``` o un ```ndarray```. Llamar a esta función es equivalente a llamar  ```matrix(datos, copy = False)```.

In [79]:
A=matrix([[1,2],[3,4]])

In [80]:
type(A)

numpy.matrix

In [81]:
A = mat('1 2 3; 4 5 6; 7 8 9')

In [82]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [83]:
3*A

matrix([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]])

In [84]:
i3 = matrix(eye(3))

In [85]:
i3

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [86]:
B=A + 2*i3

In [87]:
B

matrix([[ 3.,  2.,  3.],
        [ 4.,  7.,  6.],
        [ 7.,  8., 11.]])

Si necesitamos acceder a los renglones debemos pedir el índice

In [89]:
B[2]

matrix([[ 7.,  8., 11.]])

Para las columnas debemos pedir todos los elemtos de cada índice

In [90]:
B[:,1]

matrix([[2.],
        [7.],
        [8.]])

In [91]:
transpose(B)

matrix([[ 3.,  4.,  7.],
        [ 2.,  7.,  8.],
        [ 3.,  6., 11.]])

In [92]:
diagonal(B)

array([ 3.,  7., 11.])

In [93]:
trace(B)

21.0

Estaría padre crear una rutina que calcule el determinante de una matrix y la inversa de una matriz

In [94]:
from numpy.linalg import *

In [95]:
B1=inv(B)

In [96]:
B1

matrix([[ 0.90625,  0.0625 , -0.28125],
        [-0.0625 ,  0.375  , -0.1875 ],
        [-0.53125, -0.3125 ,  0.40625]])

In [97]:
B*B1

matrix([[ 1.00000000e+00, -2.22044605e-16,  1.11022302e-16],
        [ 2.22044605e-16,  1.00000000e+00,  2.22044605e-16],
        [-5.55111512e-16, -1.11022302e-16,  1.00000000e+00]])

In [98]:
det(B)

32.000000000000014

In [99]:
?det

### Resolver un sistema de ecuaciones 

In [100]:
A = matrix([[1, -2, 1], [0, 2, -8], [-4, 5,  9]])
b = array([0, 8,-9])

In [101]:
solve(A, b)

array([29., 16.,  3.])

In [102]:
A=mat("3 -2;1 0")

In [103]:
eigvals(A)

array([2., 1.])

In [104]:
eigenvalues, eigenvectors = eig(A)

In [105]:
eigenvalues

array([2., 1.])

In [106]:
eigenvectors

matrix([[0.89442719, 0.70710678],
        [0.4472136 , 0.70710678]])

### Archivos CSV
Los archivos en el formato de valores separados por comas (CSV) se encuentran con bastante frecuencia. A menudo, el archivo CSV es solo un volcado de un archivo de base de datos. Generalmente, cada campo en el archivo CSV corresponde a una columna de la tabla de la base de datos. Como todos sabemos, los programas de hoja de cálculo, como Excel, también pueden producir archivos CSV.